version: '3.7'


volumes:
  db_data:
  cache:
    driver: local


services:

  app:
    image: youtube-channels:latest
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - '8080:8080'
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]
    networks:
      - youtube-channels

  scheduled:
    image: youtube-channels:latest
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - db
    command: ["queues", "--scheduled"]
    networks:
      - youtube-channels

  migrate:
    image: youtube-channels:latest
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - db
    command: ["migrate", "--yes"]
    deploy:
      replicas: 0
    networks:
      - youtube-channels

  revert:
    image: youtube-channels:latest
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - db
    command: ["migrate", "--revert", "--yes"]
    deploy:
      replicas: 0
    networks:
      - youtube-channels

  sync: 
    image: youtube-channels:latest
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - db
    command: ["sync"]
    deploy:
      replicas: 0
    networks:
      - youtube-channels

  db:
    image: postgres:15-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: vapor_username
      POSTGRES_PASSWORD: vapor_password
      POSTGRES_DB: vapor_database
    ports:
      - '5432:5432'
    networks:
      - youtube-channels

  cache:
    image: redis:7.0-alpine
    restart: always
    command: /bin/sh -c "redis-server --save 20 1 --loglevel warning --requirepass $$REDIS_PASSWORD"
    env_file:
      - .env.redis
    volumes: 
      - cache:/data
    networks:
      - youtube-channels


networks:
  youtube-channels:
